[workspace]
name = "gatk-variant-calling"
version = "0.1.0"
description = "GATK variant calling workflow - from bash to Nextflow transformation"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
samtools = "*"
gatk4 = "*"
fastqc = "*"
curl = "*"
trim-galore = "*"
bcftools = "*"
bedtools = "*"
snpeff = "*"
htslib = "*"
r-base = "*"
fastp = ">=1.1.0,<2"
bwa-mem2 = ">=2.3,<3"
sra-tools = ">=3.2.1,<4"
pigz = ">=2.8,<3"